name: Python Tests

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Choose the Python version you need

    - name: Install dependencies
      run: pip install -r requirements.txt  # If you have any requirements

    - name: Run tests
      run: pytest test_functions.py

